server:
  port: 8005

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      hbm2ddl: update
      format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  #DB ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
    username: root

  servlet:
    multipart:
      maxFileSize : 10GB
      maxRequestSize : 10GB

logging:
  level:
    org:
      hibernate:
        #DB ?? ??? ????
        SQL: DEBUG
        #?????? ??? DB ?? ????
        type.descriptor.sql.BasicBinder: TRACE
